### ISSUE TITLE
Make city_name dynamic instead of a string that we hard code

### ISSUE THREAD

**Issue by TimLange31** [TimLangePN/PolyFiller#16]
Currently we have city_name as a hard coded string inserted in a few functions.
We can just read this out of the KML since it has a name variable inside of it

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.2">
<Document>
<name>AT_Dornbirn</name>
```

**Comment by bschaatsbergen** [comment]
There's already a ticket for this?
https://github.com/TimLangePN/PolyFiller/issues/11
