### ISSUE TITLE
location._raw breaks within different cities

### ISSUE THREAD

**Issue by TimLange31** [TimLangePN/PolyFiller#2]
I noticed this when running through different KML's
it uses different variables depending on where the coordinates are, for example:
`location._raw['address']['city']` or `location._raw['address']['town']`

This dependancy needs to be decoupled

**Comment by bschaatsbergen** [comment]
Resolved this through implemeting a new reverse geocoder (bing), we partition the string to just return a properly formatted street name and let the caller of the function provide us a city name @TimLangePN .
