### ISSUE TITLE
Make write_rows and write_header re-runnable 

### ISSUE THREAD

**Issue by TimLange31** [TimLangePN/PolyFiller#4]
Right now the code is not re-runnable , if you would start/stop the code it would just add another header and loop through all the polygons and add 5 points per polygon again.

We need to make sure the code is re-runnable by adding another step where it performs a check on points per polygon to see if any new polygons are added to the KML file.

**Comment by bschaatsbergen** [comment]
The application should not use `with open(file_name, 'a', newline='') as file_name:` . We are now appending instead of (re)creating the file, we should remove the file if it's existing and recreate it or create it if it's not there in the first place.
