### ISSUE TITLE
Add ZONE_CODE and other attributes to the writer

### ISSUE THREAD

**Issue by TimLange31** [TimLangePN/PolyFiller#9]
Not sure how to pick this up yet, but if we could give the KML a `ZONE_CODE `by picking for example the `Unieke ID` for that.
then we could use this `Unieke ID` for things like the ZONE_DESCRIPTION too.

**Comment by bschaatsbergen** [comment]
'Unieke ID' on polygons should represent the ZONE_CODE as there won't be any 'Unieke ID' on sellingpoints as we are the ones creating the sellingpoints after the KML has been made.
